package com.example.reports;

import com.example.fx.DatabaseConnection;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.print.PrinterJob;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.concurrent.Worker;

import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class CampaignHitsReportController {

    @FXML private ComboBox<String> campaignCombo;
    @FXML private Label lblCampaignId;
    @FXML private Label lblCampaignDesc;
    @FXML private Label lblStartDate;
    @FXML private Label lblEndDate;
    @FXML private Label lblGeneratedDate;
    @FXML private TableView<HitsRow> hitsTable;
    @FXML private TableColumn<HitsRow, String>  colCounterId;
    @FXML private TableColumn<HitsRow, String>  colDescription;
    @FXML private TableColumn<HitsRow, Integer> colHits;
    @FXML private TableColumn<HitsRow, String>  colPurchases;
    @FXML private TableColumn<HitsRow, String>  colConversion;
    @FXML private Label errorLabel;
    @FXML private VBox printableArea;
    @FXML private VBox headerBox;

    private final List<String[]> campaignList = new ArrayList<>();

    @FXML
    public void initialize() {
        setupColumns();
        loadCampaignCombo();
    }

    private void setupColumns() {
        colCounterId  .setCellValueFactory(d -> new SimpleStringProperty(d.getValue().counterId()));
        colDescription.setCellValueFactory(d -> new SimpleStringProperty(d.getValue().description()));
        colHits       .setCellValueFactory(d -> new SimpleIntegerProperty(d.getValue().hits()).asObject());
        colPurchases  .setCellValueFactory(d -> new SimpleStringProperty(d.getValue().purchases()));
        colConversion .setCellValueFactory(d -> new SimpleStringProperty(d.getValue().conversionRate()));
    }

    private void loadCampaignCombo() {
        String sql = "SELECT campaign_id, campaign_name FROM PromotionCampaign ORDER BY start_datetime DESC";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            ObservableList<String> items = FXCollections.observableArrayList();
            while (rs.next()) {
                String id      = rs.getString("campaign_id");
                String name    = rs.getString("campaign_name");
                String display = id + " – " + name;
                campaignList.add(new String[]{id, display});
                items.add(display);
            }
            campaignCombo.setItems(items);

        } catch (SQLException e) {
            errorLabel.setText("Could not load campaigns: " + e.getMessage());
        }
    }

    @FXML
    private void handleGenerateReport() {
        int selectedIdx = campaignCombo.getSelectionModel().getSelectedIndex();
        if (selectedIdx < 0) {
            errorLabel.setText("Please select a campaign first.");
            return;
        }
        errorLabel.setText("");
        loadReport(campaignList.get(selectedIdx)[0]);
    }

    private void loadReport(String campaignId) {

        headerBox.setVisible(true);
        headerBox.setManaged(true);

        String headerSql = """
                SELECT campaign_id, campaign_name, campaign_description,
                       start_datetime, end_datetime
                FROM PromotionCampaign
                WHERE campaign_id = ?
                """;
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(headerSql)) {

            ps.setString(1, campaignId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                lblCampaignId.setText("Campaign ID: " + rs.getString("campaign_id"));
                lblCampaignDesc.setText("Campaign Description: " +
                        (rs.getString("campaign_description") != null
                                ? rs.getString("campaign_description") : rs.getString("campaign_name")));
                lblStartDate.setText("Start Period: " + rs.getTimestamp("start_datetime").toLocalDateTime().toLocalDate());
                lblEndDate.setText("End Period:   " + rs.getTimestamp("end_datetime").toLocalDateTime().toLocalDate());
                lblGeneratedDate.setText("Generated: " + java.time.LocalDate.now() + "\nGenerated by IPOS-PU Operations");
            }

        } catch (SQLException e) {
            errorLabel.setText("Error loading header: " + e.getMessage());
            return;
        }

        ObservableList<HitsRow> rows = FXCollections.observableArrayList();

        String campHitsSql = "SELECT campaign_hits FROM CampaignMetrics WHERE campaign_id = ?";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(campHitsSql)) {

            ps.setString(1, campaignId);
            ResultSet rs = ps.executeQuery();
            int campHits = rs.next() ? rs.getInt("campaign_hits") : 0;
            rows.add(new HitsRow(campaignId, "Campaign hits", campHits, "N/A", "N/A"));

        } catch (SQLException e) {
            errorLabel.setText("Error loading campaign hits: " + e.getMessage());
            return;
        }

        String itemSql = """
                SELECT p.product_name, cim.item_id,
                       cim.included_in_order_count, cim.purchased_count
                FROM CampaignItemMetrics cim
                JOIN Product p ON p.item_id = cim.item_id
                WHERE cim.campaign_id = ?
                ORDER BY cim.item_id
                """;
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(itemSql)) {

            ps.setString(1, campaignId);
            ResultSet rs = ps.executeQuery();
            int itemNo = 1;
            while (rs.next()) {
                String name      = rs.getString("product_name");
                int    hits      = rs.getInt("included_in_order_count");
                int    purchased = rs.getInt("purchased_count");
                String conversionStr = hits == 0 ? "N/A" : String.format(
                        "%.0f / %.0f = %.2f (%.1f%%)",
                        (double) purchased, (double) hits,
                        (double) purchased / hits, ((double) purchased / hits) * 100);

                rows.add(new HitsRow(
                        "Item(" + itemNo + ")",
                        "\"" + name + "\" hits",
                        hits,
                        String.valueOf(purchased),
                        conversionStr
                ));
                itemNo++;
            }

        } catch (SQLException e) {
            errorLabel.setText("Error loading item metrics: " + e.getMessage());
            return;
        }

        hitsTable.setItems(rows);
    }

    @FXML
    private void handlePrint() {
        if (hitsTable.getItems().isEmpty()) {
            errorLabel.setText("Generate a report before printing.");
            return;
        }

        StringBuilder html = new StringBuilder();
        html.append("""
        <html><head><style>
        body { font-family: Arial, sans-serif; margin: 40px; font-size: 13px; }
        h2 { font-style: italic; }
        .header { display: flex; justify-content: space-between; margin-bottom: 20px; }
        .address { text-align: right; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th { background: #eee; border: 1px solid #999; padding: 6px; text-align: left; }
        td { border: 1px solid #ccc; padding: 6px; }
        .footer { margin-top: 16px; font-size: 11px; color: #555; }
        </style></head><body>
        <h2>Customer Campaign Engagement Report</h2>
        <hr/>
        <div class="header">
          <div>
    """);

        html.append("<p><b>").append(lblCampaignId.getText()).append("</b></p>");
        html.append("<p>").append(lblCampaignDesc.getText()).append("</p>");
        html.append("<p>").append(lblStartDate.getText()).append("</p>");
        html.append("<p>").append(lblEndDate.getText()).append("</p>");
        html.append("""
          </div>
          <div class="address">
            Cosymed Ltd.,<br/>
            27 Sainsbury Close,<br/>
            3, High Level Drive,<br/>
            Sydenham,<br/>
            SE26 3ET<br/>
            Phone: 0208 778 0124<br/>
            Fax: 0208 778 0125
          </div>
        </div>
        <table>
          <tr>
            <th>Counter ID</th>
            <th>Counter Description</th>
            <th>Hits Count</th>
            <th>Purchases</th>
            <th>Conversion Rate</th>
          </tr>
    """);

        for (HitsRow row : hitsTable.getItems()) {
            html.append("<tr>")
                    .append("<td>").append(row.counterId()).append("</td>")
                    .append("<td>").append(row.description()).append("</td>")
                    .append("<td>").append(row.hits()).append("</td>")
                    .append("<td>").append(row.purchases()).append("</td>")
                    .append("<td>").append(row.conversionRate()).append("</td>")
                    .append("</tr>");
        }

        html.append("</table>");
        html.append("<div class='footer'><p>").append(lblGeneratedDate.getText().replace("\n", "<br/>")).append("</p></div>");
        html.append("</body></html>");

        javafx.scene.web.WebView webView = new javafx.scene.web.WebView();
        webView.getEngine().loadContent(html.toString());

        javafx.scene.web.WebEngine engine = webView.getEngine();
        engine.getLoadWorker().stateProperty().addListener((obs, oldState, newState) -> {
            if (newState == javafx.concurrent.Worker.State.SUCCEEDED) {
                PrinterJob job = PrinterJob.createPrinterJob();
                if (job != null && job.showPrintDialog(printableArea.getScene().getWindow())) {
                    engine.print(job);
                    job.endJob();
                }
            }
        });
    }

    @FXML private void handleHome()               { navigate("/com/example/fx/Home.fxml"); }
    @FXML private void handleCatalogue()          { navigate("/com/example/fx/Catalogue.fxml"); }
    @FXML private void handleOrders()             { navigate("/com/example/fx/OrderHistory.fxml"); }
    @FXML private void handleAccount()            { navigate("/com/example/fx/Account.fxml"); }
    @FXML private void handleBasket()             { navigate("/com/example/fx/Basket.fxml"); }
    @FXML private void handleCreatePromotion()    { navigate("/com/example/fx/Promotion.fxml"); }
    @FXML private void handleManagePromotions()   { navigate("/com/example/fx/CampaignItem.fxml"); }
    @FXML private void handleActivePromotions() { navigate("/com/example/fx/ActivePromotions.fxml"); }
    @FXML private void handleReports()          { navigate("/com/example/fx/Reports.fxml"); }
    @FXML private void handleLogout()           { navigate("/com/example/fx/Login.fxml"); }

    private void navigate(String fxml) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource(fxml));
            javafx.scene.Parent root = loader.load();
            Stage stage = (Stage) hitsTable.getScene().getWindow();
            boolean wasMaximized = stage.isMaximized();
            stage.getScene().setRoot(root);
            if (wasMaximized) stage.setMaximized(true);
        } catch (IOException e) {
            errorLabel.setText("Navigation error: " + e.getMessage());
        }
    }

    public record HitsRow(
            String counterId,
            String description,
            int    hits,
            String purchases,
            String conversionRate
    ) {}
}