package com.example.reports;

import com.example.fx.DatabaseConnection;
import javafx.beans.property.SimpleDoubleProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.print.PrinterJob;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.*;
import java.time.LocalDate;

public class SalesReportController {

    @FXML private DatePicker dateFrom;
    @FXML private DatePicker dateTo;
    @FXML private Label lblStartPeriod;
    @FXML private Label lblEndPeriod;
    @FXML private Label lblGenerated;
    @FXML private VBox headerBox;
    @FXML private TableView<SalesRow> salesTable;
    @FXML private TableColumn<SalesRow, String>  colItemId;
    @FXML private TableColumn<SalesRow, String>  colDescription;
    @FXML private TableColumn<SalesRow, String>  colSoldPacks;
    @FXML private TableColumn<SalesRow, String>  colUnitPrice;
    @FXML private TableColumn<SalesRow, String>  colTotal;
    @FXML private Label errorLabel;
    @FXML private VBox printableArea;

    @FXML
    public void initialize() {
        dateFrom.setValue(LocalDate.now().minusMonths(1));
        dateTo.setValue(LocalDate.now());

        colItemId     .setCellValueFactory(d -> new SimpleStringProperty(d.getValue().itemId()));
        colDescription.setCellValueFactory(d -> new SimpleStringProperty(d.getValue().description()));
        colSoldPacks  .setCellValueFactory(d -> new SimpleStringProperty(d.getValue().soldPacks()));
        colUnitPrice  .setCellValueFactory(d -> new SimpleStringProperty(d.getValue().unitPrice()));
        colTotal      .setCellValueFactory(d -> new SimpleStringProperty(d.getValue().total()));
    }

    @FXML
    private void handleGenerateReport() {
        if (dateFrom.getValue() == null || dateTo.getValue() == null) {
            errorLabel.setText("Please select both dates.");
            return;
        }
        if (dateFrom.getValue().isAfter(dateTo.getValue())) {
            errorLabel.setText("Start date must be before end date.");
            return;
        }
        errorLabel.setText("");
        loadReport(dateFrom.getValue(), dateTo.getValue());
    }

    private void loadReport(LocalDate from, LocalDate to) {
        lblStartPeriod.setText("Start Period: " + from);
        lblEndPeriod.setText("End Period: " + to);
        lblGenerated.setText("Generated: " + LocalDate.now() + "     Generated by IPOS-PU Operations");
        headerBox.setVisible(true);
        headerBox.setManaged(true);

        String sql = """
                SELECT oi.item_id, p.product_name,
                       SUM(oi.quantity) AS total_qty,
                       oi.unit_price,
                       SUM(oi.line_total) AS total_sales
                FROM OnlineOrderItem oi
                JOIN Product p ON p.item_id = oi.item_id
                JOIN OnlineOrder o ON o.order_id = oi.order_id
                WHERE o.order_status = 'paid'
                  AND DATE(o.created_at) BETWEEN ? AND ?
                GROUP BY oi.item_id, p.product_name, oi.unit_price
                ORDER BY oi.item_id
                """;

        ObservableList<SalesRow> rows = FXCollections.observableArrayList();
        int totalQty = 0;
        double grandTotal = 0;

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setDate(1, Date.valueOf(from));
            ps.setDate(2, Date.valueOf(to));
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int qty = rs.getInt("total_qty");
                double unitPrice = rs.getDouble("unit_price");
                double total = rs.getDouble("total_sales");
                totalQty += qty;
                grandTotal += total;

                rows.add(new SalesRow(
                        String.valueOf(rs.getInt("item_id")),
                        rs.getString("product_name"),
                        String.valueOf(qty),
                        String.format("£%.2f", unitPrice),
                        String.format("£%.2f", total)
                ));
            }

            rows.add(new SalesRow(
                    "Total online sales for period",
                    "",
                    String.valueOf(totalQty),
                    "N/A",
                    String.format("£%.2f", grandTotal)
            ));

            salesTable.setItems(rows);

        } catch (SQLException e) {
            errorLabel.setText("Error loading report: " + e.getMessage());
        }
    }

    @FXML
    private void handlePrint() {
        if (salesTable.getItems().isEmpty()) {
            errorLabel.setText("Generate a report before printing.");
            return;
        }
        PrinterJob job = PrinterJob.createPrinterJob();
        if (job != null && job.showPrintDialog(printableArea.getScene().getWindow())) {
            boolean success = job.printPage(printableArea);
            if (success) job.endJob();
        }
    }

    @FXML private void handleBackToReports() { navigate("/com/example/fx/Reports.fxml", 1000, 620); }
    @FXML private void handleHome()             { navigate("/com/example/fx/Home.fxml", 800, 600); }
    @FXML private void handleCatalogue()        { navigate("/com/example/fx/Catalogue.fxml", 800, 600); }
    @FXML private void handleOrders()           { navigate("/com/example/fx/OrderHistory.fxml", 800, 600); }
    @FXML private void handleAccount()          { navigate("/com/example/fx/Account.fxml", 800, 600); }
    @FXML private void handleBasket()           { navigate("/com/example/fx/Basket.fxml", 820, 633); }
    @FXML private void handleCreatePromotion()  { navigate("/com/example/fx/Promotion.fxml", 900, 650); }
    @FXML private void handleManagePromotions() { navigate("/com/example/fx/CampaignItem.fxml", 900, 650); }

    private void navigate(String fxml, int w, int h) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource(fxml));
            Scene scene = new Scene(loader.load(), w, h);
            Stage stage = (Stage) salesTable.getScene().getWindow();
            stage.setScene(scene);
        } catch (IOException e) {
            errorLabel.setText("Navigation error: " + e.getMessage());
        }
    }

    public record SalesRow(
            String itemId,
            String description,
            String soldPacks,
            String unitPrice,
            String total
    ) {}
}