package com.example.reports;

import com.example.fx.DatabaseConnection;
import javafx.beans.property.SimpleDoubleProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.print.PrinterJob;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.*;
import java.time.LocalDate;

public class SalesReportController {

    @FXML private DatePicker dateFrom;
    @FXML private DatePicker dateTo;
    @FXML private Label lblStartPeriod;
    @FXML private Label lblEndPeriod;
    @FXML private Label lblGenerated;
    @FXML private VBox headerBox;
    @FXML private TableView<SalesRow> salesTable;
    @FXML private TableColumn<SalesRow, String>  colItemId;
    @FXML private TableColumn<SalesRow, String>  colDescription;
    @FXML private TableColumn<SalesRow, String>  colSoldPacks;
    @FXML private TableColumn<SalesRow, String>  colUnitPrice;
    @FXML private TableColumn<SalesRow, String>  colTotal;
    @FXML private Label errorLabel;
    @FXML private VBox printableArea;

    @FXML
    public void initialize() {
        dateFrom.setValue(LocalDate.now().minusMonths(1));
        dateTo.setValue(LocalDate.now());

        colItemId     .setCellValueFactory(d -> new SimpleStringProperty(d.getValue().itemId()));
        colDescription.setCellValueFactory(d -> new SimpleStringProperty(d.getValue().description()));
        colSoldPacks  .setCellValueFactory(d -> new SimpleStringProperty(d.getValue().soldPacks()));
        colUnitPrice  .setCellValueFactory(d -> new SimpleStringProperty(d.getValue().unitPrice()));
        colTotal      .setCellValueFactory(d -> new SimpleStringProperty(d.getValue().total()));
    }

    @FXML
    private void handleGenerateReport() {
        if (dateFrom.getValue() == null || dateTo.getValue() == null) {
            errorLabel.setText("Please select both dates.");
            return;
        }
        if (dateFrom.getValue().isAfter(dateTo.getValue())) {
            errorLabel.setText("Start date must be before end date.");
            return;
        }
        errorLabel.setText("");
        loadReport(dateFrom.getValue(), dateTo.getValue());
    }

    private void loadReport(LocalDate from, LocalDate to) {
        lblStartPeriod.setText("Start Period: " + from);
        lblEndPeriod.setText("End Period: " + to);
        lblGenerated.setText("Generated: " + LocalDate.now() + "     Generated by IPOS-PU Operations");
        headerBox.setVisible(true);
        headerBox.setManaged(true);

        String sql = """
                SELECT oi.item_id, p.product_name,
                       SUM(oi.quantity) AS total_qty,
                       oi.unit_price,
                       SUM(oi.line_total) AS total_sales
                FROM OnlineOrderItem oi
                JOIN Product p ON p.item_id = oi.item_id
                JOIN OnlineOrder o ON o.order_id = oi.order_id
               WHERE DATE(o.created_at) BETWEEN ? AND ?
                GROUP BY oi.item_id, p.product_name, oi.unit_price
                ORDER BY oi.item_id
                """;

        ObservableList<SalesRow> rows = FXCollections.observableArrayList();
        int totalQty = 0;
        double grandTotal = 0;

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setDate(1, Date.valueOf(from));
            ps.setDate(2, Date.valueOf(to));
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int qty = rs.getInt("total_qty");
                double unitPrice = rs.getDouble("unit_price");
                double total = rs.getDouble("total_sales");
                totalQty += qty;
                grandTotal += total;

                rows.add(new SalesRow(
                        rs.getString("item_id"),
                        rs.getString("product_name"),
                        String.valueOf(qty),
                        String.format("£%.2f", unitPrice),
                        String.format("£%.2f", total)
                ));
            }

            rows.add(new SalesRow(
                    "Total online sales for period",
                    "",
                    String.valueOf(totalQty),
                    "N/A",
                    String.format("£%.2f", grandTotal)
            ));

            salesTable.setItems(rows);

        } catch (SQLException e) {
            errorLabel.setText("Error loading report: " + e.getMessage());
        }
    }

    @FXML
    private void handlePrint() {
        if (salesTable.getItems().isEmpty()) {
            errorLabel.setText("Generate a report before printing.");
            return;
        }

        StringBuilder html = new StringBuilder();
        html.append("""
        <html><head><style>
        body { font-family: Arial, sans-serif; margin: 40px; font-size: 13px; }
        h2 { font-style: italic; }
        .header { display: flex; justify-content: space-between; margin-bottom: 20px; }
        .address { text-align: right; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th { background: #eee; border: 1px solid #999; padding: 6px; text-align: left; }
        td { border: 1px solid #ccc; padding: 6px; }
        .footer { margin-top: 16px; font-size: 11px; color: #555; }
        </style></head><body>
        <h2>IPOS-PU Sales Report</h2>
        <hr/>
        <div class="header">
          <div>
    """);

        html.append("<p>").append(lblStartPeriod.getText()).append("</p>");
        html.append("<p>").append(lblEndPeriod.getText()).append("</p>");
        html.append("""
          </div>
          <div class="address">
            Cosymed Ltd.,<br/>
            27 Sainsbury Close,<br/>
            3, High Level Drive,<br/>
            Sydenham,<br/>
            SE26 3ET<br/>
            Phone: 0208 778 0124<br/>
            Fax: 0208 778 0125
          </div>
        </div>
        <table>
          <tr>
            <th>Item ID</th>
            <th>Description</th>
            <th>Sold, packs</th>
            <th>Unit price, £</th>
            <th>Total, £</th>
          </tr>
    """);

        for (SalesRow row : salesTable.getItems()) {
            html.append("<tr>")
                    .append("<td>").append(row.itemId()).append("</td>")
                    .append("<td>").append(row.description()).append("</td>")
                    .append("<td>").append(row.soldPacks()).append("</td>")
                    .append("<td>").append(row.unitPrice()).append("</td>")
                    .append("<td>").append(row.total()).append("</td>")
                    .append("</tr>");
        }

        html.append("</table>");
        html.append("<div class='footer'><p>").append(lblGenerated.getText()).append("</p></div>");
        html.append("</body></html>");

        javafx.scene.web.WebView webView = new javafx.scene.web.WebView();
        webView.getEngine().loadContent(html.toString());

        javafx.scene.web.WebEngine engine = webView.getEngine();
        engine.getLoadWorker().stateProperty().addListener((obs, oldState, newState) -> {
            if (newState == javafx.concurrent.Worker.State.SUCCEEDED) {
                PrinterJob job = PrinterJob.createPrinterJob();
                if (job != null && job.showPrintDialog(printableArea.getScene().getWindow())) {
                    engine.print(job);
                    job.endJob();
                }
            }
        });
    }

    @FXML private void handleBackToReports()    { navigate("/com/example/fx/Reports.fxml"); }
    @FXML private void handleActivePromotions() { navigate("/com/example/fx/ActivePromotions.fxml"); }
    @FXML private void handleLogout()           { navigate("/com/example/fx/Login.fxml"); }
    @FXML private void handleHome()             { navigate("/com/example/fx/Home.fxml"); }
    @FXML private void handleCatalogue()        { navigate("/com/example/fx/Catalogue.fxml"); }
    @FXML private void handleOrders()           { navigate("/com/example/fx/OrderHistory.fxml"); }
    @FXML private void handleAccount()          { navigate("/com/example/fx/Account.fxml"); }
    @FXML private void handleBasket()           { navigate("/com/example/fx/Basket.fxml"); }
    @FXML private void handleCreatePromotion()  { navigate("/com/example/fx/Promotion.fxml"); }
    @FXML private void handleManagePromotions() { navigate("/com/example/fx/CampaignItem.fxml"); }

    private void navigate(String fxml) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource(fxml));
            javafx.scene.Parent root = loader.load();
            Stage stage = (Stage) salesTable.getScene().getWindow();
            boolean wasMaximized = stage.isMaximized();
            stage.getScene().setRoot(root);
            if (wasMaximized) stage.setMaximized(true);
        } catch (IOException e) {
            errorLabel.setText("Navigation error: " + e.getMessage());
        }
    }

    public record SalesRow(
            String itemId,
            String description,
            String soldPacks,
            String unitPrice,
            String total
    ) {}
}