module com.example.fx {
    requires javafx.controls;
    requires javafx.fxml;
    requires java.sql;
    requires jakarta.mail;
    requires spring.web;
    requires spring.boot;
    requires spring.boot.autoconfigure;
    requires spring.context;
    requires spring.beans;
    requires spring.core;
    requires java.net.http;
    requires com.fasterxml.jackson.annotation;

    opens com.example.fx to javafx.fxml;
    exports com.example.fx;
    exports com.example.email;
    opens com.example.email to spring.core, spring.beans, spring.context;
    exports com.example.basket;
    opens com.example.basket to javafx.fxml;
    exports com.example.catalogue;
    opens com.example.catalogue to javafx.fxml;
    exports com.example;
    opens com.example to spring.beans, spring.context, spring.core;
    exports com.example.payment;
    opens com.example.payment to spring.beans, spring.context, spring.core;
    opens com.example.promotion to javafx.fxml;
    exports com.example.promotion;
    opens com.example.home to javafx.fxml;
    exports com.example.home;
    opens com.example.checkout to javafx.fxml;
    exports com.example.checkout;
    opens com.example.order_confirmation to javafx.fxml;
    exports com.example.order_confirmation;
    opens com.example.reports to javafx.fxml;
    exports com.example.reports;
    exports com.example.members;
    opens com.example.members to javafx.fxml;
    opens com.example.active_promotions to javafx.fxml;
    exports com.example.active_promotions;
}